"""Handlers package composition."""

from .style_admin import style_admin_router
from .trial_category_ui import trial_category_router
from .trial_ui_v2 import trial_ui_v2_router
from .operations_bootstrap import operations_bootstrap_router
from .product_center import product_center_router
from .plan_storefront import plan_storefront_router
from .service_marketplace import service_marketplace_router
from .service_marketplace_settings import service_marketplace_settings_router
from .trial_experience import trial_experience_router
from .premium_ui_clean_buttons import premium_ui_clean_buttons_router
from .premium_ui_admin import premium_ui_admin_router
from .ui_editor_v2 import ui_editor_v2_router
from .operations import operations_router
from .home_navigation import home_navigation_router
from .operations_public import operations_public_router
from .control_center import control_center_router

style_admin_router.include_router(operations_bootstrap_router)
# Public trial pickers use presentation categories, never Rebecca inbound names.
style_admin_router.include_router(trial_category_router)
style_admin_router.include_router(trial_ui_v2_router)
# Central product manager owns sales_manage before legacy sales handlers.
style_admin_router.include_router(product_center_router)
# Paid purchases are category-first; provider mappings remain internal.
style_admin_router.include_router(plan_storefront_router)
# Service-aware routes remain for provisioning/settings and compatibility.
style_admin_router.include_router(service_marketplace_router)
style_admin_router.include_router(service_marketplace_settings_router)
style_admin_router.include_router(trial_experience_router)
style_admin_router.include_router(ui_editor_v2_router)
style_admin_router.include_router(premium_ui_clean_buttons_router)
style_admin_router.include_router(premium_ui_admin_router)
style_admin_router.include_router(operations_router)
style_admin_router.include_router(home_navigation_router)
style_admin_router.include_router(operations_public_router)
style_admin_router.include_router(control_center_router)
